version: '2'
services:
  relayer:
    container_name: hpl-relayer
    # image: gcr.io/abacus-labs-dev/hyperlane-agent:9736164-20240307-131918
    image: gcr.io/abacus-labs-dev/hyperlane-agent:3bb4d87-20240129-164519
    user: root
    # restart: always
    entrypoint: ['sh', '-c']
    command:
      - |
        rm -rf /app/config/* && \
        cp "/etc/hyperlane/agent-config.docker.json" "/app/config/agent-config.json" && \
        CONFIG_FILES="/etc/hyperlane/relayer.json" \
          ./relayer
    ports:
      - 9110:9090
    volumes:
      - ./hyperlane:/etc/hyperlane
      - ./relayer:/etc/data
      - ./validator:/etc/validator

  validator-sepolia:
    container_name: hpl-validator-sepolia
    # image: gcr.io/abacus-labs-dev/hyperlane-agent:9736164-20240307-131918
    image: gcr.io/abacus-labs-dev/hyperlane-agent:3bb4d87-20240129-164519
    user: root
    # restart: always
    entrypoint: ['sh', '-c']
    command:
      - |
        rm -rf /app/config/* && \
        cp "/etc/hyperlane/agent-config.docker.json" "/app/config/agent-config.json" && \
        CONFIG_FILES="/etc/hyperlane/validator.sepolia.json" \
          ./validator
    ports:
      - 9120:9090
    volumes:
      - ./hyperlane:/etc/hyperlane
      - ./validator:/etc/validator
      - ./validator/sepolia:/etc/data

  validator-xiontestnet1:
    container_name: hpl-validator-xiontestnet1
    # image: gcr.io/abacus-labs-dev/hyperlane-agent:9736164-20240307-131918
    image: gcr.io/abacus-labs-dev/hyperlane-agent:3bb4d87-20240129-164519
    user: root
    # restart: always
    entrypoint: ['sh', '-c']
    command:
      - |
        rm -rf /app/config/* && \
        cp "/etc/hyperlane/agent-config.docker.json" "/app/config/agent-config.json" && \
        CONFIG_FILES="/etc/hyperlane/validator.xiontestnet1.json" \
          ./validator
    ports:
      - 9121:9090
    volumes:
      - ./hyperlane:/etc/hyperlane
      - ./validator:/etc/validator
      - ./validator/xiontestnet1:/etc/data
